# Generated by Django 3.2.6 on 2022-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100, null=True)),
                ('address2', models.CharField(max_length=100, null=True)),
                ('people', models.IntegerField(null=True)),
                ('xplot', models.FloatField(null=True)),
                ('yplot', models.FloatField(null=True)),
                ('pet', models.BooleanField(default=False)),
                ('toilet', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
    ]
