# Generated by Django 3.2.6 on 2022-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='pet',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
