# Generated by Django 3.2.6 on 2022-03-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_alter_shelter_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.BooleanField(default=False, null=True)),
                ('toilet', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='toilet',
        ),
    ]
