# Generated by Django 3.2.6 on 2022-03-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20220330_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='option',
        ),
        migrations.AddField(
            model_name='shelter',
            name='pet',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='toilet',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
