# Generated by Django 4.0.4 on 2022-06-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='wearing',
            field=models.IntegerField(default=0),
        ),
    ]
