# Generated by Django 4.0.4 on 2022-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_history_wearing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='history',
            name='wearing',
            field=models.IntegerField(default=1),
        ),
    ]
