# Generated by Django 3.2.6 on 2022-03-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('tag', models.CharField(max_length=30, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
