name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build django_project/ --file Dockerfile --tag redtea89/home:amd
    - name: Push the Docker image
      run: docker push redtea89/home:amd
