# Generated by Django 4.0.4 on 2022-06-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
