# Generated by Django 4.0.4 on 2022-06-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_table_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('updated_at',)},
        ),
    ]
